name: iskra_space_domain
description: iskra_space_domain for Iskra space
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=3.4.0 <4.0.0"

dev_dependencies:
  test: ^1.25.0
  very_good_analysis: ^6.0.0
