name: flutter-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: flutter analyze
      - run: flutter test --coverage || true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: app-coverage
          path: coverage/

      - name: Install melos
        run: dart pub global activate melos
      - name: Bootstrap workspace
        run: ~/.pub-cache/bin/melos bootstrap
      - name: Analyze packages
        run: ~/.pub-cache/bin/melos run analyze
      - name: Test packages
        run: ~/.pub-cache/bin/melos run test
